### ISSUE TITLE
PAC 默认代理地址问题

### ISSUE THREAD

**Issue by R0uter** [breakwa11/gfw_whitelist#10]
PAC 默认代理地址为 `var wall_proxy = "SOCKS5 127.0.0.1:1080;";`
此处可否在生成的时候加一句，变成这样：
`var wall_proxy = "SOCKS5 127.0.0.1:1080;SOCKS 127.0.0.1:1080";`
——————
理由：
Safari 不支持 Socks5，第一次用的时候忘记了这茬捣鼓了好久……加上这句以提高（默认）兼容性？

**Comment by breakwa11** [comment]
可以在生成的时候加一个参数指定用你设定的字符串的

**Comment by R0uter** [comment]
这个我知道，已经自助修好~
