### ISSUE TITLE
bit.ly  每次遇到它，都会打不开。

### ISSUE THREAD

**Issue by R0uter** [breakwa11/gfw_whitelist#12]
提示无效的变量。我使用域名白名单。

**Comment by breakwa11** [comment]
估计是bug，但近期估计没有空

**Comment by R0uter** [comment]
👌我自己先想想办法~

**Comment by R0uter** [comment]
已解决：
`if ( domains === undefined ) {
		return true;
	}`
改为：
`if ( domains === undefined ) {
		return false;
	}`
即可，你看看是不是你写错了还是我没有看懂？我不会javascript，但改了确实正常了，目前没发现问题哦。

**Comment by breakwa11** [comment]
貌似是真的写错了

**Comment by breakwa11** [comment]
修了
