### ISSUE TITLE
姐姐呀！你readme怎么写成了这样！

### ISSUE THREAD

**Issue by R0uter** [breakwa11/gfw_whitelist#20]
`main.py -o whitelist.pac -p "SOCKS5 127.0.0.1:1080; SOCKS 127.0,0,1080;"`

我手懒直接复制了，然后……………………没有然后了。
`SOCKS 127.0,0,1080` → `SOCKS 127.0.0.1:1080`

**Comment by breakwa11** [comment]
修好了。。。。。。
