### ISSUE TITLE
请问，你的 pac 文件如何修改，可以让 https 协议的地址全部直连？

### ISSUE THREAD

**Issue by jzp820927** [breakwa11/gfw_whitelist#24]
请问，你的 pac 文件如何修改，可以让 https 协议的地址全部直连？

还有个问题，你这个项目里面一共有 7 个 PAC 文件，都有什么区别呢？ 一般该用哪个 PAC ？

**Comment by R0uter** [comment]
https全部直连这个我不会，不过一般用 whitelist就对了，这个是域名白名单，还有个 whiteiplist，这个是基于IP的，体积上小一些，但容易dns泄露得配合无污染的dns才行。但好处是可能相对前者不需要频繁更新。

**Comment by jzp820927** [comment]
好吧，谢谢！
