### ISSUE TITLE
可否出wiki自助添加一些白名单

### ISSUE THREAD

**Issue by ysmintor** [breakwa11/gfw_whitelist#25]
# 自助添加
自己对于pac不太了解，希望可以有些指导，方便添加自己认为需要的白名单。查看wiki没有内容。所以不知道可否简单介绍如何操作？

目前已经做得很好了，对于白名单我是使用自己上传到github然后用raw方式去下载，主要是用于xx-net，这样处理基本没有什么问题，非常感谢。再配合ss一些常用的软件用于更新，查一些资料和看一些tutorial都非常方便。

**Comment by majie1993** [comment]
README 里写了，把你要自定义的域名放到 `lists/custom.py` 里，运行一遍生成即可https://github.com/breakwa11/gfw_whitelist#代码生成使用方法

**Comment by ysmintor** [comment]
谢谢，自己不太会使用python。在windows下安装了python后通过cmd命令就可以运行这个吗？

**Comment by majie1993** [comment]
如果你的需求仅限于 xx 网站走代理，xx 不走，那还不如直接用 SwitchyOmega 之类的，在浏览器级别做黑白名单，只把 ss 当成一个 socks5 代理
当你使用了 Pac 控制整个电脑的联网，且需要调整比如公司内部工具和它访问的内部域名的代理，这个时候才需要去自定义

**Comment by ysmintor** [comment]
你可能没太明白我意思。我目前确实是通过SwitchyOmega+白名单方式通过xx-net访问。系统则是白名单pac走ss方式。由于黑名单方式更新和gfw相比这下，更新速度比不过gfw变动。一些学习站点能打开，但是一些图片有时候就打不开，反观白名单方式解决了这个问题，速度上也快。即使一些网站本来可以不通过ss或者xx-net，但通过走白名单方式减少一些打开页面奇怪的问题，速度慢一些也是值得。

**Comment by ysmintor** [comment]
你可能没太明白我意思。我目前确实是通过SwitchyOmega+白名单方式通过xx-net访问。系统则是白名单pac走ss方式。由于黑名单方式更新和gfw相比这下，更新速度比不过gfw变动。一些学习站点能打开，但是一些图片有时候就打不开，反观白名单方式解决了这个问题，速度上也快。即使一些网站本来可以不通过ss或者xx-net，但通过走白名单方式减少一些打开页面奇怪的问题，速度慢一些也是值得。

**Comment by majie1993** [comment]
插件里不要创建 PAC Profile，直接创建一个 Proxy Profile。既然用了这个插件，为啥需要白名单？所有不能访问的域名和访问速度慢的都会被它列出来，一键添加到插件自己的规则里就可以了啊。浏览器访问的网站有限而且透明可见，添加成本也不高，完全没必要白名单

**Comment by sobasin** [comment]
作者是否考虑出一份AutoProxy格式的list? pac虽用途更广，但配合SwitchyOmega仍显得灵活性不足。
如果是AutoProxy格式，自助添加或修改某条规则就容易多了。

**Comment by ysmintor** [comment]
明白了，这方面一直没有深入地学习过。白名单是黑名单确实效果不如白名单，一些网站一打开加载慢，然后是加载miss一些元素，索性就用白名单，体验上比黑名单好多了。

--------------

另外报告一个问题是本地系统win10 使用白名单，搜索很慢，不用或者用全局的方式就快。不知道什么原因造成。

**Comment by R0uter** [comment]
我根据作者白名单项目自己精简了一个小项目专门做白名单，目前我自己根据使用情况手动更新，以后会写小蜘蛛来爬，你可以看我仓库：）

**Comment by ysmintor** [comment]
## R0uter的项目非常不错，不过目前用shadowsocks-rss客户端配置已经满足使用了，chrome上针对不出图的问题确实是用whitelist的体验好多了。
