### ISSUE TITLE
Safari 无法使用pac

### ISSUE THREAD

**Issue by pypykim** [breakwa11/gfw_whitelist#3]
Safari 8.0.2 无法使用pac
https://raw.githubusercontent.com/kqz901002/gfw-whitelist-pac/master/whiteiplist.pac
OSX 10.10.1

**Comment by breakwa11** [comment]
呃，有具体点的情况说明么？你是如何使用的？直接用github链接我不确定是不是好用，有试过项目提供的动态地址吗

**Comment by kqz901002** [comment]
的确是不能直接使用github链接，改用本地地址http://127.0.0.1:9999/proxy.pac就ok了，谢谢
