### ISSUE TITLE
请教 breakwa11，如何在 whiteiplist.pac 中添加优酷为白名单？

### ISSUE THREAD

**Issue by mwacgi** [breakwa11/gfw_whitelist#33]
我目前的网络环境中使用 whiteiplist.pac 一直效果都很好，除了偶尔看优酷视频的时候（提示所在的所在的地区xxxxx之类的），希望在 whiteiplist.pac 中增加针对优酷的白名单，请问如何修改？谢谢！

**Comment by breakwa11** [comment]
暂时还不支持自己修改
