### ISSUE TITLE
导致Adobe Creative Cloud （离线激活）失效

### ISSUE THREAD

**Issue by sarkdavidson** [breakwa11/gfw_whitelist#34]
Adobe 系列离线激活采用了Hosts屏蔽方法，亲测全局代理模式下导致了Hosts失效，白名单也导致这个问题，请问能怎样解决？

127.0.0.1	activate.adobe.com
127.0.0.1	practivate.adobe.com
127.0.0.1	ereg.adobe.com
127.0.0.1	wip3.adobe.com
127.0.0.1	activate.wip3.adobe.com
127.0.0.1	3dns-3.adobe.com
127.0.0.1	3dns-2.adobe.com
127.0.0.1	adobe-dns.adobe.com
127.0.0.1	adobe-dns-2.adobe.com
127.0.0.1	adobe-dns-3.adobe.com
127.0.0.1	ereg.wip3.adobe.com
127.0.0.1	activate-sea.adobe.com
127.0.0.1	wwis-dubc1-vip60.adobe.com
127.0.0.1	activate-sjc0.adobe.com
127.0.0.1	hl2rcv.adobe.com
127.0.0.1	lmlicenses.wip4.adobe.com
127.0.0.1	lm.licenses.adobe.com
127.0.0.1	na2m-pr.licenses.adobe.com
127.0.0.1	ims-na1-prprod.adobelogin.com
127.0.0.1	na4r.services.adobe.com
127.0.0.1	na1r.services.adobe.com
127.0.0.1	hlrcv.stage.adobe.com

**Comment by breakwa11** [comment]
所有的dns解析在服务端，本地这样设置是没用的，所以最好不要设置系统代理，让它直连
