### ISSUE TITLE
求推荐 SwitchyOmega 上有白名单用法

### ISSUE THREAD

**Issue by coeusite** [breakwa11/gfw_whitelist#36]
请问 SwitchyOmega 上有没有什么推荐的白名单用法？

我目前是把 https://github.com/breakwa11/gfw_whitelist/raw/master/ss_bypass.action 加到 Rule List 里作为白名单，但是尚不清楚 CN-IP 该怎么用。

**Comment by breakwa11** [comment]
你这用法是错的

**Comment by coeusite** [comment]
直接用 whiteiplist.pac 还需要额外解决 DNS 污染
而使用 whitelist.pac 的话诸如 ipip.net 或 edu.cn 这类地址和 CN-IP 都并未被包含在白名单里
而 PAC 好像只支持本地临时微调，不支持长期的。

所以我才想使用 Switch Profile + 订阅白名单 + 手动微调。

**Comment by breakwa11** [comment]
我没有白名单提供订阅
