### ISSUE TITLE
【请教】请问PAC中如何写才能判断要访问的域名或IP是否属于大陆

### ISSUE THREAD

**Issue by chenxiccc** [breakwa11/gfw_whitelist#43]
【请教】
你好，鉴于现在被封的网站太多，有些网站即使未被封也速度很慢，所以希望能够在PAC中自动判断访问的域名或者IP是否属于大陆，如果不是，则走代理。
这种方式跟白名单方式的区别是，大陆的网站新建速度也很快，而白名单的更新速度肯定是远慢于大陆新网站或域名的产生的。通过判断域名归属，可以比白名单模式减少误判。

在[SpechtLite](https://github.com/zhuhaow/SpechtLite)项目中，可以通过配置文件来判断访问地址所属国家是否是大陆

` \# Reject requests based on the IP address of the host.
    file: ~/.SpechtLite/rejectiprange
    adapter: reject
  - type: country
  \# When the location is unknown. Usually this means this is resolved an Intranet IP.
    country: CN
    match: true
    adapter: direct
  - type: country
  \# When the location is unknown. Usually this means this is resolved an Intranet IP.
    country: --
    match: true
    adapter: direct`

不知在PAC文件中是否能够实现同样的功能？

**Comment by breakwa11** [comment]
这功能早就写好了，请直接参考源代码

**Comment by Explorare** [comment]
请问这个功能在哪个文件的哪一段呢？
