### ISSUE TITLE
whiteiplist.pac小问题及其他

### ISSUE THREAD

**Issue by catshitz** [breakwa11/gfw_whitelist#46]
1. ss配合whiteiplist.pac可打开btkitty.bid并搜索任意种子（btkitty.bid/search/***.html），却不能打开任意种子页面的二级域名（btkitty.bid/torrent/***.html）和种子下载页面域名（storebt.com/torrent/***.html），需关闭代理才能打开；希望可以将其加入whiteiplist.pac；
2. 近一个月来使用whiteiplist.pac常遇到国外网盘图床及论坛类网站打开缓慢或持续空白（chrome），切换全局代理则正常，网络环境等各项未变，不知何故，望知晓。
3. 一如既往支持破娃姐。
以上です。

**Comment by breakwa11** [comment]
whiteiplist.pac 只管IP，不管域名，你必须确认你在无DNS污染情况下才能使用这个PAC
