### ISSUE TITLE
Chinalist的链接已经404了

### ISSUE THREAD

**Issue by monkey008** [breakwa11/gfw_whitelist#49]
如何添加Chinalist？

**Comment by breakwa11** [comment]
你说的什么鬼？

**Comment by monkey008** [comment]
看你说明里建议使用： Adblock Plus ＋ Easylist ＋ Chinalist来屏蔽广告
现在AdblockPlus里默认的是EasyList China+EasyList
或许是我不了解 但是Chinalist不是在14年就宣布停止更新了吗？我看你的说明里为Chinalist挂上了超链接，还以为又有人开始维护了...结果跳转过去是404

**Comment by breakwa11** [comment]
这是14年的文档，就没更新过
