### ISSUE TITLE
什么情况？为何好几个项目被删了？被请去喝茶了？

### ISSUE THREAD

**Issue by erguotou520** [breakwa11/gfw_whitelist#56]

**Comment by Z4HD** [comment]
知道那么多干嘛，Close issue，请

**Comment by erguotou520** [comment]
因为我做了个基于ssr的gui啊，所以我也要关心啊

**Comment by Z4HD** [comment]
@erguotou520 
给你两个TG链接，多看少说，谨言慎行。

* [@esutv](https://t.me/esutv)
* [@shadowsocksr](https://t.me/shadowsocksr)

>***重要警示***：截止至2017-7-28，Telegram上的esu.tv频道并不能证明其行为是Esu团体的集体行动，亦无任何信息表明其是恶俗先辈。 esu.tv恶俗小鬼可能性微存。***出于对您个人隐私的保护，建议您保持**谨言慎行**。
