### ISSUE TITLE
对最近发生的事情感到遗憾和难过

### ISSUE THREAD

**Issue by qjaden** [breakwa11/gfw_whitelist#57]
唉

**Comment by vajvip** [comment]
刚逛知乎看到，挺震惊的，作为一名学生的确不应该承受着么大的压力。只能说唯小人难伺候，放宽心。我想用过ssr的人都应该尊重你的贡献，你起码让数十万人拥有了他们想得到的东西，这应该是你人生中浓墨重彩的一笔。感谢。

**Comment by tphz** [comment]
感谢曾经的努力！看不惯那些人的嘴脸。

**Comment by akiraxiao** [comment]
缅怀

**Comment by sailosha** [comment]
我现在打这句话的流量是我自己用ssr建的双cn2通道，
有些人就是觉得有些猪比其他动物更加平等更加自由，
因为他既不理解麻烦的技术又没办法为自己争取自由

**Comment by evolutionjay** [comment]
感谢作者无私奉献, 无论如何, 你干过伟大的事.  祝前程似锦, 平安健康.

**Comment by shanlinfeiniao** [comment]
感谢！

**Comment by Zzz97siao** [comment]
感谢破娃的付出

**Comment by a17uk** [comment]
谢谢破娃的付出，你会后继有人的，吸血鬼杀死每一只报晓的公鸡也是无法阻止黎明的到来的。总得有人肩负历史的重任，无论这世界有多少恶毒的小人。祝福破娃，希望你能有肉体翻墙的那天，欢迎来袋鼠国哦，哈哈。

**Comment by kj415j45** [comment]
感谢破娃的付出。同时也希望通过备份能恢复ssr社区的生机与活力。

**Comment by JimTang67** [comment]
没什么好说的，要说只有一句：谢谢！

**Comment by xsaddata** [comment]
需要帮助么？我们团队可以接下来开发，可以完全换个名字重新开始的。

**Comment by 1688pc** [comment]
感谢作者付出

**Comment by JHrockice** [comment]
致敬！

**Comment by Jingyu-Yan** [comment]
本来只是发现项目突然被删除，然后找了一下最新版，发现我之前提过意见你已经添加了功能，想来留言感谢一下。但是没想到这个事情真的闹得这么过分，恶的让人恶心。谢谢你为我们平常人做的这些。（本来想开个问题道谢，然后删除掉，但是已经有相关的我就跟一下，只怪这网站没有留言之类的东西。。）

**Comment by LexsionLee** [comment]
感谢作者，致敬！

**Comment by idongliming** [comment]
用ssr的代理流量留言，谢谢你

**Comment by Martinjon146001** [comment]
感谢作者，致敬！

**Comment by TwilightHome** [comment]
每一个在黑暗中发出呼喊的人都值得感谢

**Comment by ghost** [comment]
感谢作者，致敬！
同时我大概明白发生了什么事情
哎 希望越变越好把
